export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
