export const EDIT_PROJECT = "EDIT_PROJECT";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";

//------------- Project Saga ---------------
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
export const GET_ALL_PROJECT_SAGA = "GET_ALL_PROJECT_SAGA";
export const UPDATE_PROJECT_SAGA = "UPDATE_PROJECT_SAGA";
export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";
export const GET_PROJECT_DETAIL_API = "GET_PROJECT_DETAIL_API";
