export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const CHANGE_TASK_MODAL = "CHANGE_TASK_MODAL";
export const CHANGE_ASSIGNEES = "CHANGE_ASSIGNEES";
export const REMOVE_USER_ASSIGN = "REMOVE_USER_ASSIGN";

//------------------------ Saga -------------------
export const CREATE_TASK_API = "CREATE_TASK_API";
export const GET_TASK_DETAIL_API = "GET_TASK_DETAIL_API";
export const UPDATE_TASK_STATUS_API = "UPDATE_TASK_STATUS_API";
export const UPDATE_TASK_API = "UPDATE_TASK_API";
export const HANDLE_CHANGE_POST_API_SAGA = "HANDLE_CHANGE_POST_API_SAGA";
