export const LOGIN_INFO = "LOGIN_INFO";
export const GET_USER_SEARCH = "GET_USER_SEARCH";
export const GET_USER_PROJECT_BY_ID = "GET_USER_PROJECT_BY_ID";
export const EDIT_USER = "EDIT_USER";

//------------------------------ Saga ---------------------
export const USER_SIGNIN_SAGA = "USER_SIGNIN_SAGA";
export const USER_SIGNUP_SAGA = "USER_SIGNUP_SAGA";
export const GET_USER_SAGA = "GET_USER_SAGA";
export const ADD_USER_PROJECT_SAGA = "ADD_USER_PROJECT_SAGA";
export const REMOVE_USER_PROJECT_SAGA = "REMOVE_USER_PROJECT_SAGA";
export const GET_USER_PROJECT_BY_ID_SAGA = "GET_USER_PROJECT_BY_ID_SAGA";
export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";
export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
